name: Terraform CI

on:
  push:
    branches: [ "main" ]
    paths: [ "terraform/**" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Init
        run: terraform init -input=false
      - name: Validate
        run: terraform validate
      - name: Plan
        run: terraform plan -input=false
